name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd Backend-Development/grow-with-us-backend
        npm install
        cd ../../Frontend-Development/grow-with-us
        npm install

    - name: Run Backend Tests
      run: |
        cd Backend-Development/grow-with-us-backend
        npm test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        JWT_SECRET: test-secret
        JWT_REFRESH_SECRET: test-refresh-secret

    - name: Run Frontend Tests
      run: |
        cd Frontend-Development/grow-with-us
        npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        echo "Add your deployment commands here"
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}